### PR TITLE
Add  Segment (Broadcast) Text messages

### PR DESCRIPTION
**Pull request by kuzmany**
https://github.com/mautic/mautic/pull/7879

### CODE REVIEW

**Comment by npracht** [comment]
to confirm @kuzmany it is using the send broadcast command of email ? Or another broadcast for text messages ?

**Comment by kuzmany** [comment]
Yes, it's same command and same options (channel, ids ...). 
Without options command trigger emails and sms with one touch.

**Comment by RCheesley** [comment]
@mautic/education-team-leaders @kuzmany we will need to bring this PR over to the new documentation repo at https://github.com/mautic/mautic-documentation in time for the 3.2 release.

Would also be good if we could have some materials to promote this feature - tutorial, video, use cases etc.

**Comment by LeonOltmanns** [comment]
@RCheesley @kuzmany I will make some time to write that after the Mauticon! :)

**Comment by RCheesley** [comment]
Have updated the documentation on the new repo so I'll close this PR down.

**Pull request closed without merging**
