### PR TITLE
JS monitoring docs

### PR DESCRIPTION
**Pull request by escopecz**

### CODE REVIEW

**Comment by funnyprinter** [comment]
@escopecz @dbhurley just being curious, how the mautic tracking works in detail. Maybe you could enhance the documentation in regards to some conflict situations:

1. **Reappearing users on multiple devices:** What happens if the same email-address appears a second time? So a user comes on device-a and enters email address which is assigned to the profile through new js tracking class. Later the same user comes on device-b and enters the same email-address in another form. Emails are unique, so this results in a conflict situation. What happens now?

2. **Changing Data by User:** Is there any best practice on how to combine approved data with new user entered data? E.g filling the system with data from crm system. Using this data to do an email campaign. Now user A changes Realname-A to Fakename-A. Roundtripping data back to the crm system now would bring bad data into the crm. Whats a good strategy to avoid this?

**Comment by escopecz** [comment]
@funnyprinter Thanks for the questions! 

1. Mautic uses email as a unique identifier. So the contacts will be merged into one. The new submitted data will override the old one (if the contact sends the same data).

2. You can use either the additional tracking data in the tracking request, the API or the webhooks. It's up to you what is the best fit for your use case. 

This PR is closed, so there is no way how to add something to it. But feel free to add whatever you think is valuable:
https://github.com/mautic/documentation#how-to-contribute-to-the-docs

**Comment by manuelfink** [comment]
@escopecz Regarding 2, my thoughts where more like having a two fields per property for example name_internal and name_external and the possibilty to access this field as a "merged" field. Meaning if the user changes or accidently overwrites his name, my internaly set name will still be used. However if I get a new user from the web, always his external name will be used since no internal name is set yet. For automating emails this access rule is fun, because than i still can just add the field "name" to the email and it automatically selects the right value.

Side node, just changed my username from @funnyprinter to my real name @manuelfink

**Comment by escopecz** [comment]
@manuelfink you can create as many fields as you need and store the information in them from different sources. But I don't know how to merge them into one in the email template. However, if you have an idea how to build it, feel free to create a new feature request at https://github.com/mautic/documentation/issues

**Pull request merged**
