### PR TITLE
Update French documentation due to recent updates

### PR DESCRIPTION
**Pull request by npracht**

### CODE REVIEW

**Comment by npracht** [comment]
Hm. I didn't update my master branch... There are few missing files... :)
I'll update you when i'm ready.

**Comment by escopecz** [comment]
@npracht I don't understand the comment

> I'll update you when i'm ready.

Does it mean we should wait with the merge?

**Comment by npracht** [comment]
Yes, obviously i missed some file.. !
I keep you updated.

**Comment by npracht** [comment]
@escopecz, I AM DONE :D

**Comment by escopecz** [comment]
Looks good! Thanks for your hard work! 👍

**Pull request merged**
