### PR TITLE
Amazon webhook

### PR DESCRIPTION
**Pull request by wittwerch**
Documentation for the Amazon webhook https://github.com/mautic/mautic/pull/2312

### CODE REVIEW

**Comment by mbrinson** [comment]
Thanks for this documentation Wittwerch.  Could you also add a little explanation of how to set up the webhook itself on the Mautic side?

For example, should we leave all "Webhook Events" unchecked, or do one or more of them need to be checked?

Is it normal for the URL we point to for the Webhook to issue a 500 internal server error if we visit it in a web browser?  On the Amazon SNS side, I can see that my subscription ID has changed from "PendingConfirmation" to a Subscription ARN number, but when I check on Mautic under the Webhook Log, I see "No Webhooks Logs.  This webhook hasn't been executed yet so there aren't any logs available"

Also, when I send a "test payload" under the webhook in Mautic, I always get an "Error detected!" message back.

Thanks so much for any help / direction you can provide!

**Comment by wittwerch** [comment]
The only part to configure in Mautic is actually to switch to the Amazon mailer. You don't need to configure any webhook at all, that is done in the background by Mautic itself.
I know that calling /mailer/amazon/callback leads to a 500. That happens when you call that url with a GET instead of a POST. That was not possible before, but somehow the routing changed.
Anyway. If the subscription changed all looks good. That means that the Amazon webhook is working and that it was confirmed.

**Comment by mbrinson** [comment]
Thanks so much for your response Wittwerch, I sure appreciate it.

So, you don't even have to set up the "Monitored Inbox Settings"?  Something must be wrong with my configuration because I've tested by sending to some fake email addresses, and I never get a "Bounce" status back.  The contacts I have tested with do not show a bounce status.  I've tried it with and without the SNS / Webhook set up, and with/without the Monitored Inbox Settings approach.

**Comment by mbrinson** [comment]
I've been reading more in the Amazon SES documentation and I came across this:

"Bounces – The recipient's mail server permanently rejected the email. This event corresponds to hard bounces. Soft bounces are only included when Amazon SES fails to deliver the email after retrying for a period of time."

I wonder if my problem is that I'm getting soft bounces and Mautic doesn't pick up on that?  The email address I'm testing the bounce with is for a fake domain that I made up that I verified doesn't exist.  So, I'm guessing this would be a soft bounce, right?

**Pull request merged**
