### PR TITLE
FIX JS Tracking code JSON error

### PR DESCRIPTION
**Pull request by katzueno**
The current documentation doesn't wrap the custom fields with double quotation which won't pass the information at all.

I've fixed the sample codes for English, Japanese, and French.

I've noticed there was a section missing in Japanese. So I've added the additional translation.

Thanks.

### CODE REVIEW

**Comment by escopecz** [comment]
This doesn't make sense. The JS syntax is correct. See for example https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Object_literals

**Comment by hissy** [comment]
@escopecz OK, you mean it is a Object, not a JSON, right? If so, I misunderstood it should be a JSON data.

Integration plugins uses json_encode() to pass variables to `mt()` function.

WordPress: https://github.com/mautic/mautic-wordpress/blob/6e78dbea2517be7bc57395df3e64dae951cc2f05/wpmautic.php#L143
concrete5: https://github.com/mautic/mautic-concrete5/blob/746a871183e2953ec10c2bd0369371b59acd8b25/src/Concrete/Asset/Tracker.php#L89

**Comment by escopecz** [comment]
That's OK too. JSON stands for JavaScript Object Notation. If you dump JSON to JS code, it will become Javascript object. But that doesn't mean that the current syntax in the docs is wrong. 

Could you please revert the `"` changes and leave only the new paragraph in `jp/contacts/contact_monitoring.md`?

**Comment by katzueno** [comment]
@escopecz OK done.

**Pull request merged**
