### PR TITLE
Add some helpful tips for cron jobs

### PR DESCRIPTION
**Pull request by dobesv**

### CODE REVIEW

**Comment by dbhurley** [comment]
Thanks for the commit! I am very glad to see you submitting a PR :) There's a minor typo in the last sentence. 

```You can thus us this to figure out whether or not the cron job is running successfully and on schedule.```

**Comment by dobesv** [comment]
Thanks, I fixed it.

**Comment by escopecz** [comment]
:+1:

**Comment by dbhurley** [comment]
Merged. Thank you @dobesv :+1:

**Pull request merged**
